#ifndef TRAP_H
#define TRAP_H

typedef enum {
	INSTRUCTION_ADDRESS_MISALIGNED = 0,
	INSTRUCTION_ACCESS_FAULT = 1,
	ILLEGAL_INSTRUCTION = 2,
	BREAKPOINT = 3,
	LOAD_ADDRESS_MISALIGNED = 4,
	LOAD_ACCESS_FAULT = 5,
	STORE_AMO_ADDRESS_MISALIGNED = 6,
	STORE_AMO_ACCESS_FAULT = 7,
	ENVIRONMENT_CALL_FROM_U_MODE = 8,
	ENVIRONMENT_CALL_FROM_S_MODE = 9,
	ENVIRONMENT_CALL_FROM_M_MODE = 11,
	INSTRUCTION_PAGE_FAULT = 12,
	LOAD_PAGE_FAULT = 13,
	STORE_AMO_PAGE_FAULT = 15,
	DOUBLE_TRAP = 16,
	SOFTWARE_CHECK = 18,
	HARDWARE_ERROR = 19,
} exception_code;

typedef enum {
	SUPERVISOR_SOFTWARE_INTERRUPT = 1,
	MACHINE_SOFTWARE_INTERRUPT = 3,
	SUPERVISOR_TIMER_INTERRUPT = 5,
	MACHINE_TIMER_INTERRUPT = 7,
	SUPERVISOR_EXTERNAL_INTERRUPT = 9,
	MACHINE_EXTERNAL_INTERRUPT = 11,
	COUNTER_OVERFLOW_INTERRUPT = 13,
} interrupt_code;

extern volatile int trap_hit;

void trap_init(void);

#endif
